In [1]:
## importing numpys and pandas
import numpy as np 
import pandas as pd 


In [2]:
## show all nupmy methods available in numpy 
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'Bytes0',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'Datetime64',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Str0',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'Uint64',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__getattr__',
 '__git_revision__',
 '__loader__',

In [3]:
# show current numpy version 
print(np.__version__)

1.20.3


In [6]:
#Q  Create a new array of 2*2 integers, without initializing entries.
## empty will create array with random values 
a=np.empty([2,2],int)
a
np.empty([3,3],int)

array([[-514152288,        600,          0],
       [         0,    3997793,    7340142],
       [   6619182,    7340141,          0]])

In [7]:
## Q given an array create array of same type a 
np.empty_like(a)
## this will create array of 2X2 with random no 

array([[ 1416411795, -1532251131],
       [ 1157051029,   -19952541]])

In [13]:
# Q create an array from list 
## remember array is not df  its 2 rows 3 column matrix 
np.array([[1,2,3],[4,5,6]],int)

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
## Q create an 2 dimension 3 X 3 array with one on diagonal and zeros on other basically eigen array 
##Creates an array of 3 x 3 with the main diagonal of 1
bEigen=np.eye(3)
bEigen

np.eye(3,k=1) ## here k is index of diagonal starting 
#help(np.eye)

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [24]:
#syntax identity(n, dtype=None, *, like=None)
c=np.identity(3)
c
#help(np.identity)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [26]:
## create and array with filled with no 1  of dataype float
a=np.ones([3,2],float)
a

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [28]:
# arange([start,] stop[, step,], dtype=None, *, like=None)
#Return evenly spaced values within a given interval Create 1 D array .
x=np.arange(4,16,2,float)
x
#help(np.arange)

array([ 4.,  6.,  8., 10., 12., 14.])

In [31]:
# Q create 3X2 arrays Filled with Zeros 
b=np.zeros([3,2],int)
b

In [32]:
# Q copy above structure but float data Type 
np.zeros_like(b,float)

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [35]:
# note array take only two postional arguments 
# Q create array 3 X 2 filled with 5
np.full([3,2],5,float)

array([[5., 5.],
       [5., 5.],
       [5., 5.]])

In [36]:
## create an array of 1 to 10 and multiply it by 7 
np.arange(1,10)*7

array([ 7, 14, 21, 28, 35, 42, 49, 56, 63])

# Creating array from existing Data 

In [ ]:
# create an array of list [1,2,3]
np.array([1,2,3])

In [43]:
# covert list to array 
a=[1,2]
b=np.array(a)
print("type of a:{},type of B:{}".format(type(a),type(b)))


type of a:<class 'list'>,type of B:<class 'numpy.ndarray'>


In [47]:
## create an copy of a which has different ids 
a=np.array([1,2,3])
y=np.copy(a)
print(id(a),a ,"\n", id(y),y)
## note :like  create shallow copy

2580840803280 [1 2 3] 
 2580835846160 [1 2 3]


## numerical Ranges 

In [48]:
# arange([start,] stop[, step,], dtype=None, *, like=None)
np.arange(1,100,3,float)

array([ 1.,  4.,  7., 10., 13., 16., 19., 22., 25., 28., 31., 34., 37.,
       40., 43., 46., 49., 52., 55., 58., 61., 64., 67., 70., 73., 76.,
       79., 82., 85., 88., 91., 94., 97.])

In [51]:
#help(np.linspace)
# linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)
#     Return evenly spaced numbers over a specified interval.
#  Returns `num` evenly spaced samples, calculated over the
#     interval [`start`, `stop`].
# not logspace and linspace are similar 


Help on function linspace in module numpy:

linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)
    Return evenly spaced numbers over a specified interval.
    
    Returns `num` evenly spaced samples, calculated over the
    interval [`start`, `stop`].
    
    The endpoint of the interval can optionally be excluded.
    
    .. versionchanged:: 1.16.0
        Non-scalar `start` and `stop` are now supported.
    
    .. versionchanged:: 1.20.0
        Values are rounded towards ``-inf`` instead of ``0`` when an
        integer ``dtype`` is specified. The old behavior can
        still be obtained with ``np.linspace(start, stop, num).astype(int)``
    
    Parameters
    ----------
    start : array_like
        The starting value of the sequence.
    stop : array_like
        The end value of the sequence, unless `endpoint` is set to False.
        In that case, the sequence consists of all but the last of ``num + 1``
        evenly spaced samples, so that 

In [55]:
print(np.linspace(1,10,2,False))
## here linspace(starrt,stop,SampleNo,notEvenlyspaces)
print(np.linspace(1,10,2))
# here evenly spaced sample no 

[1.  5.5]
[ 1. 10.]


## building matrix 

In [56]:
## Q Let X = np.array([[ 0, 1, 2, 3], [ 4, 5, 6, 7], [ 8, 9, 10, 11]]). Get the diagonal of X, that is, [0, 5, 10].

X = np.array([[ 0, 1, 2, 3], [ 4, 5, 6, 7], [ 8, 9, 10, 11]])
X.diagonal()

array([ 0,  5, 10])

In [58]:
##Q Create a 2-D array whose diagonal equals [1, 2, 3, 4] and 0's elsewhere.
np.diagflat([1,2,3,4])
# diagflat(v, k=0)
#     Create a two-dimensional array with the flattened input as a diagonal.
# help(np.diagflat)

Help on function diagflat in module numpy:

diagflat(v, k=0)
    Create a two-dimensional array with the flattened input as a diagonal.
    
    Parameters
    ----------
    v : array_like
        Input data, which is flattened and set as the `k`-th
        diagonal of the output.
    k : int, optional
        Diagonal to set; 0, the default, corresponds to the "main" diagonal,
        a positive (negative) `k` giving the number of the diagonal above
        (below) the main.
    
    Returns
    -------
    out : ndarray
        The 2-D output array.
    
    See Also
    --------
    diag : MATLAB work-alike for 1-D and 2-D arrays.
    diagonal : Return specified diagonals.
    trace : Sum along diagonals.
    
    Examples
    --------
    >>> np.diagflat([[1,2], [3,4]])
    array([[1, 0, 0, 0],
           [0, 2, 0, 0],
           [0, 0, 3, 0],
           [0, 0, 0, 4]])
    
    >>> np.diagflat([1,2], 1)
    array([[0, 1, 0],
           [0, 0, 2],
           [0, 0, 0]])



In [62]:
#Q Create an array which looks like below. array([[ 0., 0., 0., 0., 0.], [ 1., 0., 0., 0., 0.], [ 1., 1., 0., 0., 0.]])
# help(np.tri)
# 
# tri(N, M=None, k=0, dtype=<class 'float'>, *, like=None)
#     An array with ones at and below the given diagonal and zeros elsewhere.N = NO OF ROWS IN array

np.tri(3,5,-1)


array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0.]])

In [63]:
# help(np.reshape)
# reshape(a, newshape, order='C')
#     Gives a new shape to an array without changing its data.

Help on function reshape in module numpy:

reshape(a, newshape, order='C')
    Gives a new shape to an array without changing its data.
    
    Parameters
    ----------
    a : array_like
        Array to be reshaped.
    newshape : int or tuple of ints
        The new shape should be compatible with the original shape. If
        an integer, then the result will be a 1-D array of that length.
        One shape dimension can be -1. In this case, the value is
        inferred from the length of the array and remaining dimensions.
    order : {'C', 'F', 'A'}, optional
        Read the elements of `a` using this index order, and place the
        elements into the reshaped array using this index order.  'C'
        means to read / write the elements using C-like index order,
        with the last axis index changing fastest, back to the first
        axis index changing slowest. 'F' means to read / write the
        elements using Fortran-like index order, with the first index
        c

In [ ]:
# help(np.reshape)
# reshape(a, newshape, order='C')

# array manupulation 


In [85]:
#Q Q1. Let x be a ndarray [10, 10, 3] with all elements set to one. Reshape x so that the size of the second dimension equals 150.
# nd array =An array object represents a multidimensional, homogeneous array
#  |  of fixed-size items. 
# here 10 rows , 3 columns , 10 each
# help(np.ndarray)
## note important  for numpy functions array, ones ,zeros etc (plane , row, coulmn ) default plane is one.
#  plane  is represented by []
# x=np.ones([10,10,3])
# x.reshape(150)
# help(np.ones)
# x.size
# help(np.reshape)
# reshape(array, newshape, order='C')


x = np.ones([10, 10, 3])
out = np.reshape(x, [-1, 150])
print(out)
assert np.allclose(out, np.ones([10, 10, 3]).reshape([-1, 150]))



     


[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1.]]


In [90]:
# Q Q2. Let x be array [[1, 2, 3], [4, 5, 6]]. Convert it to [1 4 2 5 3 6].
x=np.array([[1,2,3],[4,5,6]])
print(x)
out1 = np.ravel(x, order='F')
out2 = x.flatten(order="F")
assert np.allclose(out1, out2)
print (out1)

# help(np.ravel)
# # ravel(a, order='C')
# #     Return a contiguous flattened array.orders can be C,F,A,K WHERE F ORDER IS LIKE 
# RAVEL MEANS FLATTEN 


[[1 2 3]
 [4 5 6]]
[1 4 2 5 3 6]
Help on function ravel in module numpy:

ravel(a, order='C')
    Return a contiguous flattened array.
    
    A 1-D array, containing the elements of the input, is returned.  A copy is
    made only if needed.
    
    As of NumPy 1.10, the returned array will have the same type as the input
    array. (for example, a masked array will be returned for a masked array
    input)
    
    Parameters
    ----------
    a : array_like
        Input array.  The elements in `a` are read in the order specified by
        `order`, and packed as a 1-D array.
    order : {'C','F', 'A', 'K'}, optional
    
        The elements of `a` are read using this index order. 'C' means
        to index the elements in row-major, C-style order,
        with the last axis index changing fastest, back to the first
        axis index changing slowest.  'F' means to index the elements
        in column-major, Fortran-style order, with the
        first index changing fastest, an

In [100]:
# Let x be array [[1, 2, 3], [4, 5, 6]]. Get the 5th element. ie 5 
x=np.array([[1, 2, 3], [4, 5, 6]])
# Flat iterator object to iterate over arrays,It allows iterating over the array as if it were a 1-D array,
# help(x.flat)
#  note index start from 0 
out1 = x.flat[4]
# out1
out2 = np.ravel(x)[4]  # selecting 4th index 
# help(np.ravel)
# ravel(a, order='C'): Return a contiguous/continuous  flattened array
print(out1,out2)

5 5


In [110]:
# Q4. Let x be an arbitrary 3-D array of shape (3, 4, 5). Permute the dimensions of x such that the new shape will be (4,3,5).
a=np.zeros([3,4,5])
# note: array only take two values ie aray(list/tuple of homogenous type , second data type )
b=np.reshape(a,[4,3,5])
print(a,"\n",b)


[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]] 
 [[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


AssertionError: 

In [114]:
# Q4. Let x be an arbitrary 3-D array of shape (3, 4, 5). Permute the dimensions of x such that the new shape will be (4,3,5).
# changing or transposing in 3-d
a=np.zeros([3,4,5])
# note: array only take two values ie aray(list/tuple of homogenous type , second data type 


x = np.zeros((3, 4, 5))
out1 = np.swapaxes(x, 1, 0)
out2 = x.transpose([1, 0, 2])
assert out1.shape == out2.shape ,"false"
print (out1.shape)


(4, 3, 5)


In [118]:
# help(np.swapaxes)
# # swapaxes(a, axis1, axis2) :Interchange two axes of an array.
# help(np.transpose)
# transpose(a, axes=None): Reverse or permute the axes of an array; returns the modified array.
    

In [122]:
# Q5. Let x be an arbitrary 2-D array of shape (3, 4). Permute the dimensions of x such that the new shape will be (4,3).
x=np.ones([3,4])
out1 = np.swapaxes(x, 1, 0)
out2 = x.transpose()
out3 = x.T
assert out1.shape == out2.shape == out3.shape
print (out1.shape)

# note shape will give the shape of array 


(4, 3)


In [125]:
# Q5. Let x be an arbitrary 2-D array of shape (3, 4). Insert a nex axis such that the new shape will be (3, 1, 4).
x = np.zeros((3, 4))
print np.expand_dims(x, axis=1).shape

# note: expand_dims(a, axis)
#     Expand the shape of an array.

SyntaxError: invalid syntax (Temp/ipykernel_1312/4259536212.py, line 3)

In [ ]:
# help(np.expand_dims)


# array string operations 

In [128]:
# Q1. Concatenate x1 and x2
x1 = np.array(['Hello', 'Say'], dtype=np.str_)
x2 = np.array([' world', ' something'], dtype=np.str_)
out = np.char.add(x1, x2)
print(out)

['Hello world' 'Say something']


In [133]:
# Q2. Repeat x three time element-wise.
x1=np.array(['hello','how','are','you'],np.str_)
# x1
out = np.char.multiply(x1, 3)
print(out)

['hellohellohello' 'howhowhow' 'areareare' 'youyouyou']


In [135]:
# 3-1. Capitalize the first letter of x element-wise.
# Q3-2. Lowercase x element-wise.
# Q3-3. Uppercase x element-wise.
# Q3-4. Swapcase x element-wise.
# Q3-5. Title-case x element-wise.
capitalized = np.char.capitalize(x1)
lowered = np.char.lower(x1)
uppered = np.char.upper(x1)
swapcased = np.char.swapcase(x1)
titlecased = np.char.title(x1)
print("capitalized =", capitalized)
print("lowered =", lowered)
print("uppered =", uppered)
print("swapcased =", swapcased)
print("titlecased =", titlecased)

# Note: np.char have string manupulation methos like  capitalization of first word , lowered , uppered , swapcase, titlecase 

capitalized = ['Hello' 'How' 'Are' 'You']
lowered = ['hello' 'how' 'are' 'you']
uppered = ['HELLO' 'HOW' 'ARE' 'YOU']
swapcased = ['HELLO' 'HOW' 'ARE' 'YOU']
titlecased = ['Hello' 'How' 'Are' 'You']


In [137]:
# Q4. Make the length of each element 20 and the string centered / left-justified / right-justified with paddings of _.


x = np.array(['hello world', 'say something'], dtype=np.str_)
centered = np.char.center(x, 20, fillchar='_')
left = np.char.ljust(x, 20, fillchar='_')
right = np.char.rjust(x, 20, fillchar='_')

print("centered =", centered)
print("left =", left)
print("right =", right)


# note: np.char.center  for centralization of word 
#     np.char.ljust ie left adjust , rjust for rjust , fillchar='<charToBeFilled>'


centered = ['____hello world_____' '___say something____']
left = ['hello world_________' 'say something_______']
right = ['_________hello world' '_______say something']


In [ ]:
# Q6. Insert a space between characters of x.


x = np.array(['hello world', 'say something'], dtype=np.str_)
out = np.char.join(" ", x)
print(out)



     


In [139]:
# Q7-1. Remove the leading and trailing whitespaces of x element-wise.
# Q7-2. Remove the leading whitespaces of x element-wise.
# Q7-3. Remove the trailing whitespaces of x element-wise.

x = np.array(['   hello world   ', '\tsay something\n'], dtype=np.str_)
stripped = np.char.strip(x)
lstripped = np.char.lstrip(x)
rstripped = np.char.rstrip(x)
print("stripped =", stripped)
print("lstripped =", lstripped)
print("rstripped =", rstripped)

stripped = ['hello world' 'say something']
lstripped = ['hello world   ' 'say something\n']
rstripped = ['   hello world' '\tsay something']


In [140]:
# Q8. Split the element of x with spaces.
x = np.array(['Hello my name is John'], dtype=np.str_)
out = np.char.split(x)
print(out)

[list(['Hello', 'my', 'name', 'is', 'John'])]


In [142]:
# Q9. Split the element of x to multiple lines.
x = np.array(['Hello\nmy name is John'], dtype=np.str_)
out = np.char.splitlines(x)
print(out)

[list(['Hello', 'my name is John'])]


In [150]:
# Q10. Make x a numeric string of 4 digits with zeros on its left.
x = np.array(['34'], dtype=np.str_)
out = np.char.zfill(x, 4)
print(out)

# note: zfill(a, width): Return the numeric string left-filled with zeros
# help(np.char.zfill)

['0034']


In [152]:
# Q11. Replace "John" with "Jim" in x.
x = np.array(['Hello nmy name is John'], dtype=np.str_)
out = np.char.replace(x, "John", "Jim")
print(out)


['Hello nmy name is Jim']


In [154]:
# Q14. Count the number of "l" in x, element-wise.

x = np.array(['Hello', 'my', 'name', 'is', 'Lily'], dtype=np.str_)
out = np.char.count(x, "l")
print(out)
help(np.char.count)

# note:count(a, sub, start=0, end=None)
#     Returns an array with the number of non-overlapping occurrences of
#     substring `sub` in the range [`start`, `end`].
#  here a means array 

[2 0 0 0 1]
Help on function count:

count(a, sub, start=0, end=None)
    Returns an array with the number of non-overlapping occurrences of
    substring `sub` in the range [`start`, `end`].
    
    Calls `str.count` element-wise.
    
    Parameters
    ----------
    a : array_like of str or unicode
    
    sub : str or unicode
       The substring to search for.
    
    start, end : int, optional
       Optional arguments `start` and `end` are interpreted as slice
       notation to specify the range in which to count.
    
    Returns
    -------
    out : ndarray
        Output array of ints.
    
    See also
    --------
    str.count
    
    Examples
    --------
    >>> c = np.array(['aAaAaA', '  aA  ', 'abBABba'])
    >>> c
    array(['aAaAaA', '  aA  ', 'abBABba'], dtype='<U7')
    >>> np.char.count(c, 'A')
    array([3, 1, 1])
    >>> np.char.count(c, 'aA')
    array([3, 1, 0])
    >>> np.char.count(c, 'A', start=1, end=4)
    array([2, 1, 1])
    >>> np.char.count(c, 

In [156]:


# Q16-1. Check if each element of x is composed of digits only.
# Q16-2. Check if each element of x is composed of lower case letters only.
# Q16-3. Check if each element of x is composed of upper case letters only.

x = np.array(['Hello', 'I', 'am', '20', 'years', 'old'], dtype=np.str_)
out1 = np.char.isdigit(x)
out2 = np.char.islower(x)
out3 = np.char.isupper(x)
print("Digits only =", out1)
print("Lower cases only =", out2)
print("Upper cases only =", out3)



Digits only = [False False False  True False False]
Lower cases only = [False False  True False  True  True]
Upper cases only = [False  True False False False False]


# numpy revison notes this will be sufficient for big data 

numpy --> scipy 
numpy for computation based out of c  ---> numpy is for homogenenous data type
dtype ---> numpy datatype 
[] ---> represet row 
[[1,2,3][3,4,5]] === 2 rows 3 colomns as default 1 plane 
np.array(plane,row,cloumns)
np.array ==> constructor for multidimentional array
np.dim ---> gives dimenstions
np.shape ---> gives shape  --> tuple of array dimentions
np.dtype--> gives data type , datatype of numpy elements 
np.astype(T) ---> as data type 
np.copy()
np.reshape() ===> returns the different copy with different id 
np.resize ===> returns change of shape of same array 

array methods ---> A.astype(t)
                -> A.copy()
                -> A.reshape(_
                ->A.resize()
                ->A.mean()
                ->A.var()
                
universal funtions (functions) ---> +,-,/,*

dot products and cross products 
np.dot(obj1,obj2)
np.cross(obj1,obj2)
